name: eigo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml=6.0.2
  - numpy=2.2.5
  - pandas=2.3.1
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - scikit-learn=1.7.1
  - scikit-image=0.25.2
  - openpyxl=3.1.5
  - pip
  - pip:
      - diffusers==0.35.1
      - datasets==3.6.0
      - openai-clip==1.0.1
      - python-pptx==1.0.2
      - accelerate==1.10.0
      - cma==4.0.0
      - opencv-python==4.*
      - torch==2.8.0
      - transformers==4.55.2
      - torchvision==0.23.*
