seed_path: null  # Path to a file containing seeds (set to null if not using a file). If null, uses the 'seed' value below.
seed: 42  # Default seed value for reproducibility
cuda: 0  # GPU device ID to use (e.g., 0 for the first GPU). If no GPU is available, falls back to CPU.
predictor: 2  # Predictor type: 0 for SAM, 1 for LAION V1, 2 for LAION V2
num_inference_steps: 1  # Number of inference steps for the diffusion model during image generation
height: 512  # Height of the generated image in pixels
width: 512  # Width of the generated image in pixels
num_iterations: 1000  # Number of iterations for the Adam optimization process
model_id: stabilityai/sdxl-turbo  # Model ID for the Stable Diffusion XL pipeline
results_folder: results  # Folder to save results, including images and logs
alpha: 1.0  # Weight for the aesthetic score in the combined fitness function
beta: 0.0  # Weight for the CLIP score in the combined fitness function
max_aesthetic: 10  # Maximum possible aesthetic score (used for normalization)
max_clip: 0.50  # Maximum possible CLIP score (used for normalization)
prompt_per_categorie: 3  # Number of prompts to sample per category from the dataset
prompt_sample_seed: 42  # Seed for sampling prompts from the dataset
adam_lr: 5e-3  # Learning rate for the Adam optimizer
adam_weight_decay: 1e-05  # Weight decay for the Adam optimizer
adam_eps: 1e-8  # Epsilon value for numerical stability in the Adam
adam_beta1: 0.85  # Beta1 parameter for the Adam optimizer
adam_beta2: 0.98  # Beta2 parameter for the Adam optimizer