# Define source directories containing the result folders
source_dirs: [
  "results/ga_mutated_clip_laionv2_sdxlturbo_42_a60_b40",
  "results/ga_empty_clip_laionv2_sdxlturbo_42_a60_b40",
  "results/promptist_clip_laionv2_sdxlturbo_42_a60_b40",
  ]
# Define display names for each of the above methods
method_names: [
  "Initial Prompt", # Baseline, do not change
  "GA Mutated",
  "GA Empty",
  "Promptist",
]

algorithm_labels: [
    ["baseline", "SDXL Turbo (no optimization)"],
    ["ga_mutated", "GA Mutated"],
    ["ga_empty", "GA Empty"],
    ["promptist", "Promptist"],
]

save_folder: "results_processed_tokens"

aesthetic_max: 10.0
clip_max: 0.5